name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
           docker pull fluidattacks/forces:new
           docker images
           ftoken="eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJjaXBoZXJ0ZXh0IjoicW1jeHFGMVdLbXBZcnQyZ1V4bTFnUURuRGg3U1lGZHNqekk0ejNfNTM0WDBCS25zLXJkQlQ1amJPUEtQZllpY3cxTlZ0T0V2cVNMRUkwRlhKYjlRZU9nOHJVTENLbVEtRWNpY0paYXdDZTZuZmV0T190SnF5Vmt6RHpSZkJraW84d2xFak42ajZabGZfMWNoWmYzeGJoeTBJUVFkajZzR2dwTHl5aTlSMXBqc2Y3YzFjS1J2aF9uWWxweFZYdWVMSF9tUDhMTUZwZmlMWE5RTHpIZVlTelh6Skc5N3FyWlIyOFEyVFdyMmg5OWFUQTU1QlhvLSIsImVuY3J5cHRlZF9rZXkiOiJOZWZYZVJKdmtaRERBZVpEeVdOZkJ0WW5nWjRNM1ZzQ1M0WUUyYkExNWYwIiwiaGVhZGVyIjp7Iml2IjoibzdOVGI2aVVMNHpJVU04aCIsInRhZyI6InV0UjZ5UTNVX0NLbDllUWR3UXE5ZFEifSwiaXYiOiJEQy1Bd3FWVkpWY0JqV3R5IiwicHJvdGVjdGVkIjoiZXlKaGJHY2lPaUpCTWpVMlIwTk5TMWNpTENKbGJtTWlPaUpCTWpVMlIwTk5JbjAiLCJ0YWciOiJaaHFsTUhyZHE4bVgxWlVRRnFVS3NnIn0.-ZRChZ7sN-k2iW6HDQLFq_jzXfojj_sFG5KUElqA6zNmepqxdD1m5bjnTvCclAhmu_5gAIZ4s1FW2R-LxLvcjQ"
           docker run --rm -i fluidattacks/forces:new forces --token ${ftoken} -vvvv --repo-name bwapp --strict
