name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
           docker pull fluidattacks/forces:new
           docker images
           ftoken="eyJhbGciOiJIUzUxMiJ9.eyJjaXBoZXJ0ZXh0IjoiNDZVaVlwWlJLbmpXQVJXOUYxQ3luME00TUZQZjctbzdTbjc3c3JvZ2lPbnVIR3duR1Z6ZzBUNmFSQWJEQWJJSE9lQ1h5TUpZOXdlRlRLSmcyN29TNFJaS2thM19LRTZ5VzU2anA4cm5ydzBFUlJNZnRvazZ1OGY4RXVPZDdrVG5IdEVpVTg0blZnRHlqaXVzNEZaS25xcktSUzF2NE9kX2h2VUF6WFBnYThQT0NJZzZwUnAxU1NsZ0lGSWw4bzYyIiwiZW5jcnlwdGVkX2tleSI6IkRON2JXNFJRYndqOGs5d1ZYd0hUQ1RmbWhEbHkxc3huWUVVUzNVNlpZa2MiLCJleHAiOjE2ODMwNjM0NzIsImhlYWRlciI6eyJpdiI6IldPUTBIOHZqaGFTaXFJRTIiLCJ0YWciOiJ4R3NObTJ0U244R1cwaGJaS2Qxd3N3In0sIml2IjoiSUV2b0hxeENuSENEbUUxRiIsInByb3RlY3RlZCI6ImV5SmhiR2NpT2lKQk1qVTJSME5OUzFjaUxDSmxibU1pT2lKQk1qVTJSME5OSW4wIiwic3ViIjoiYXBpX3Rva2VuIiwidGFnIjoiSkV1WnAyaFliQ0hVNURkVTJ3aXhHQSJ9.qOQgTAmSpZKhA19UyFokph-aupOy1NdtNIB1JAAZYSD-sh7gUHpRxShiRLYplYUONYGI38oko9-aJT6pyhu_yQ"
           docker run --rm -i fluidattacks/forces:new forces --token ${ftoken} -vvvv --repo-name bwapp --strict
